/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appparque;

import com.mycompany.appparque.frames.Barraquinha;
import com.mycompany.appparque.frames.Brinquedo;
import com.mycompany.appparque.frames.Caixa;
import com.mycompany.appparque.frames.Funcionario;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author luizh
 */
public class FrameParque extends javax.swing.JFrame {
    private String driverDB = "com.mysql.cj.jdbc.Driver";
    private String usuario = "root";
    private String senha = "mysql";
    private String url = "jdbc:mysql://localhost:3306/parque";
    private Connection con;
    private Statement stm;
    private ResultSet res;
    
    /**
     * Creates new form FrameParque
     */
    public FrameParque() {
        try {
            Class.forName(driverDB);
            con = DriverManager.getConnection(url, usuario, senha);
            JOptionPane.showMessageDialog(rootPane, "Conectado com sucesso!");
        } catch (ClassNotFoundException ex) {
            System.out.println("Erro de configuracao de classe!");
        } catch (SQLException ex) {
            System.out.println("Erro de Conexao!");
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jDesktop = new javax.swing.JDesktopPane();
        jRBrinquedo = new javax.swing.JRadioButton();
        jRBarraquinha = new javax.swing.JRadioButton();
        jRCaixa = new javax.swing.JRadioButton();
        jRFuncionario = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("jRadioButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRBrinquedo);
        jRBrinquedo.setText("Brinquedo");
        jRBrinquedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBrinquedoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBarraquinha);
        jRBarraquinha.setText("Barraquinha");
        jRBarraquinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBarraquinhaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRCaixa);
        jRCaixa.setText("Caixa");
        jRCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCaixaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRFuncionario);
        jRFuncionario.setText("Funcionario");
        jRFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFuncionarioActionPerformed(evt);
            }
        });

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktop.setLayer(jRBrinquedo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(jRBarraquinha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(jRCaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(jRFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktop.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addComponent(jRBrinquedo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGroup(jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBarraquinha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jRBrinquedo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBarraquinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRFuncionario)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRCaixaActionPerformed

    private void jRFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRFuncionarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRBarraquinha.isSelected()) {
            Barraquinha form = new Barraquinha();
            jDesktop.add(form);
            form.show();
        }
        else if (jRBrinquedo.isSelected()) {
            Brinquedo form = new Brinquedo();
            jDesktop.add(form);
            form.show();
        }
        else if (jRFuncionario.isSelected()) {
            Funcionario form = new Funcionario(con, stm, res);
            jDesktop.add(form);
            form.show();
        }
        else {
            Caixa form = new Caixa();
            jDesktop.add(form);
            form.show();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRBrinquedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBrinquedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBrinquedoActionPerformed

    private void jRBarraquinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBarraquinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBarraquinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameParque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JRadioButton jRBarraquinha;
    private javax.swing.JRadioButton jRBrinquedo;
    private javax.swing.JRadioButton jRCaixa;
    private javax.swing.JRadioButton jRFuncionario;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
